server:
  port: 8088
spring:
  output:
    ansi:
      enabled: never
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: sa
    driver-class-name: com.mysql.jdbc.Driver
  http:
      multipart:
        max-file-size: 10000Mb
        max-request-size: 10000Mb

